### PR TITLE
Update for VSCode 1.52

### PR DESCRIPTION
**Pull request by moltenform**
Thought I'd add one more update.

Thanks again for the useful project! I'm currently juggling Mac, Windows, and Linux code, so it's helpful to have consistent keybindings.

### CODE REVIEW

**Comment by codebling** [comment]
Awesome, thanks! 

It looks like #4 was caused by a keybinding for a plugin. Do you think we can eliminate that by filtering out the `extension.` keybindings?

**Comment by moltenform** [comment]
Oh, that was caused by one of my extensions! I didn't realize it would pick up even disabled extensions! I would have thought that disabling the extensions would be enough.

Will submit another revision, thanks for letting me know.

**Comment by codebling** [comment]
In the keybinding files that I retrieved, I had seen commented-extensions at the towards the end of the file, but I did not realise that any extensions were added to defaults. It doesn't really make sense to me that extensions should be able to add default keybindings, so I didn't expect that at all.

Does it make sense to add a line in your scripts to remove any line bound to `command` `extension.*`?  Regex would look like `{[^]+"command": "extension\.[^}]+},`

**Comment by codebling** [comment]
@moltenform should I make a change to your script, or do you think there's a better way to handle the extensions problem?

**Comment by moltenform** [comment]
Thanks for reminding me, will address tonight.

**Comment by codebling** [comment]
Cool, thanks! No pressure. Also, though, let me know your thoughts on strategy. What's your plan?

**Comment by moltenform** [comment]
Couldn't do it quick last night, as unfortunately, some extensions don't namespace their commands under `extension.` For example, I have an extension `bookmarks` that registers commands `bookmarks.jumpToNext` and there's not a clear way to know it is an extension. And not all extensions will have a command like `workbench.view.extension.foo`.

So as a workaround I'll see if I can use https://stackoverflow.com/questions/49667641/launch-vsc-with-clean-or-custom-profile to start vscode pointing `extensions_root` to an empty dir, which I hope should work.

**Comment by codebling** [comment]
Nice. I can confirm that setting `--extensions-dir` works. Internal/included extensions are still listed, but external/installed extensions are not.

**Review by codebling — APPROVED** [review]

**Comment by codebling** [comment]
Awesome, thanks!!

**Pull request merged**
