### PR TITLE
Update Node version from 16 to LTS

### PR DESCRIPTION
**Pull request by tshino**
The Node version 16 has been reached the end of life last month.

I found that it seems we can specify `lts` to `node-version` option.
https://github.com/actions/setup-node

### CODE REVIEW

**Comment by tshino** [comment]
oops

**Comment by codebling** [comment]
Even with correct version spec, doesn't seem to run on Windows. What should we do?

**Comment by tshino** [comment]
I was able to reproduce the failure with the exact same message on my local Windows.
```
Failed to run
```
I replaced `vscode-test` with `@vscode/test-electron` and the issue seemed to be fixed locally.
Let's see it on CI.

**Comment by tshino** [comment]
I think the problem has gone!
Thanks for the fix.

**Review by codebling — APPROVED** [review]

**Comment by codebling** [comment]
Thanks! nice

**Pull request merged**
