### PR TITLE
for vscode@1.48.2 on linux

### PR DESCRIPTION
**Pull request by zimtsui**

### CODE REVIEW

**Comment by codebling** [comment]
Thanks!! Is this from a fresh install?

**Comment by zimtsui** [comment]
yes, without any plugin enabled

**Comment by codebling** [comment]
Merged, thanks!

**Comment by moltenform** [comment]
I'd like to contribute the latest for Windows etc. I didn't see the default bindings in VSCode's source, could someone point me to it / explain how you guys generated the files? I don't mind writing python scripts to transform it into the right syntax for this project.

This will be very useful for me unmapping all of the default bindings, and I saw on VSCode's project page that @selendym had requested a way to do this too.

**Comment by codebling** [comment]
@moltenform So far all of codes are fed manually from from VS Code settings. I have dug into the [VS Code source](https://github.com/microsoft/vscode) before on a few occasions, and I constantly dig in just far enough to see that it's nowhere obvious and then realize that I have other things to do :)


A PR would be welcome! If you'd like to submit a PR, you can:
Use Quick Open (ctrl+P on Windows and Linux, cmd+P on Mac) and type in `Open Default Keyboard Shortcuts (JSON)`. 
Copy the contents of the file that is opened and paste them into your OS mapping file (e.g. `windows.keybindings.json`), *replacing* the contents. From there, you can simply open a PR, I usually run `sed` to add the negative keybindings. 

I haven't updated the keybindings in a bit (I was mainly using this when I was running both Mac and Linux systems and got frustrated when keybindings were different and muscle memory failed), so thanks, your comment is a good reminder that I should update these, and possibly add some instructions for contributing. 

If I don't see a Windows PR from you in the next few days I'll go ahead and spin up a VM and update them, let me know if that's easier!

**Comment by moltenform** [comment]
Thanks! A PR is in progress!

**Pull request merged**
