### PR TITLE
Add check for existing PR to avoid duplication by the scheduled workflow

### PR DESCRIPTION
**Pull request by tshino**

### CODE REVIEW

**Comment by codebling** [comment]
Hey! I have been thinking about this as well. I have a slightly different approach but I think this is a good solution right now. I'll merge

I have been waiting a few days for moltenform to answer my questions in the other PR, but l guess we won't be getting any guidance from moltenform. Do you think there is any point in avoiding comments in the JSON?

**Comment by tshino** [comment]
Thank you for accepting!
It is still not working correctly though.

> Do you think there is any point in avoiding comments in the JSON?

I think it depends on how people treat the files.
If someone uses software that does not accept JSON with comments, definitely the comments are troublesome.
If everyone uses the files directly with tolerant software or just handles them by hand, there is no problem.

**Review by BenF-lively — APPROVED** [review]

**Comment by tshino** [comment]
Hi, I think it has been completed.

If there is an existing PR that is authored by "github-actions" and with exactly the same title the workflow is going to create, the workflow will not commit the change and not create a PR.

**Comment by codebling** [comment]
> One of the main reasons for my Python script was to create a clean diff, so that looking at the history of the file would be reasonable. People would send in files with different whitespacing and create noisy diffs. Having cleaner diffs let us check that the right things are being added to the file.

Ok that's great to know! It's very true that the PRs were often extremely noisy. I think if we're auto-generating them, we can leave that stuff in now.  

> I think it depends on how people treat the files.

The use-case here is just to paste these into VS Code, which can handle the comments.
 
I was worried that BenF had a different use-case which required no comments, but based on what was said above it doesn't seem to be a blocker, and I think it's handy to have the comment with the version at the top.

> If there is an existing PR that is authored by "github-actions" and with exactly the same title the workflow is going to create, the workflow will not commit the change and not create a PR.

```
a PR for the same version found
```
Looks like it's working! Going to try one thing

**Comment by codebling** [comment]
Awesome, thanks!!

**Pull request merged**
